# Generated by Django 4.1.4 on 2023-01-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
